(*
   ISO TC184/SC4/WG12 N11541 - ISO/TS 10303-1742 Shape composition - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N8045
*)

SCHEMA Shape_composition_mim;

USE FROM Shape_property_assignment_mim;	-- ISO/TS 10303-1032
	USE FROM Shape_aspect_definition_schema
    (composite_shape_aspect, 
     composite_group_shape_aspect,
     composite_unit_shape_aspect);

	USE FROM Shape_dimension_schema (dimensional_location);
	
END_SCHEMA;


